## 析构函数绝对不要吐出异常，如果析构函数可能抛出异常，析构函数应该捕获任何异常并吞下他们
## 如果客户需要对异常做反应，class应该提供一个普通函数执行该操作

### 析构函数不要吐出异常

```
class Widget 
{
public:
    ~Widget() {... throw} 
}
```
void dosomething()
{
    vector<Widget> v(10); // 这个临时对象在析构的时候可能会抛出异常
}

为了使得自动调用解析函数，可以这么设计
```
class DBConnection
{
public:
    static DBConnection create(); // 返回一个DBConnection对象
    void close(); // 关闭联机，失败则抛出异常
}
```
为了保证客户不忘记自动的调用close(),一个合理的想法是创建管理类class
```
class DBConn
{
public:
    ~DBConn()
    {
        db.close();
    }
private:
    DBConnection db;
}
```
有以下的代码
```
{
    DBConn dbc(DBConnection::create());
}
```
假如close调用失败，则析构函数会传播该异常

### 有两种方法可以解决问题
强迫结束
```
DBConn:: ~DBConn()
{
    try: {db.close();}
    catch () 
    {
        std::abort(); // 强迫结束
    }
}
```
吞下异常
```
DBConn::~DBConn()
{
    try: {db.close();}
    catch () { log} // 仅仅记录
}
```
如果客户想主动关闭呢？？<br>
这两种方法都无法把客户主动关闭但出错的这种情况提交给客户

### 重新设计DBConn接口
DB可以自己提供一个close函数，给用户一个机会
```
class DBConn
{
public:
    void close()
    {
        db.close();
        closed = true;
    }
    ~DBConn()
    {
        if (!closed)
        {
            try 
            {
                db.close();
            }
            catch () 
            {
                .... // 记下对close的调用失败
            }
        }
    }
private:
    DBConnection db;
    bool closed;
}
```
